title: "SWA + Jekyll + Decap"
url: "https://jolly-sand-06d352c0f.3.azurestaticapps.net"

collections:
  updates:
    output: true
    permalink: /updates/:title/
  jobs:
    output: true
    permalink: /jobs/:title/

defaults:
  - scope: { path: "_updates", type: "updates" }
    values: { layout: update }
  - scope: { path: "_jobs", type: "jobs" }
    values: { layout: job }

markdown: kramdown
kramdown:
  input: GFM


