title: "Demo Jekyll + Decap"
url: "AZURE_URL"
baseurl: ""

collections:
  updates:
    output: true
    permalink: /updates/:title/
  jobs:
    output: true
    permalink: /jobs/:title/

defaults:
  - scope:
      path: ""
      type: "updates"
    values:
      layout: "update"
  - scope:
      path: ""
      type: "jobs"
    values:
      layout: "job"

markdown: kramdown
kramdown:
  input: GFM


